[server]
hosts = 0.0.0.0:5232

[auth]
type = htpasswd
htpasswd_filename = /config/users
htpasswd_encryption = bcrypt

[storage]
filesystem_folder = /data/collections
hook = (git status --porcelain | awk '{print $2}' | /venv/bin/python3 /usr/local/bin/create_birthday_calendar.py || true) && git add -A && (git diff --cached --quiet || git -c user.email=radicale@elg.gg -c user.name=Radicale commit -m 'Changes by %(user)s')
