version: '3'
services:
  bl_elg_gg:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bl_elg_gg.rule=Host(`bl.elg.gg`)"
      - "traefik.http.routers.bl_elg_gg.entrypoints=web"
      - "traefik.http.routers.bl_elg_gg-secure.rule=Host(`bl.elg.gg`)"
      - "traefik.http.routers.bl_elg_gg-secure.entrypoints=websecure"
      - "traefik.http.routers.bl_elg_gg-secure.tls.certresolver=myresolver"
    networks:
      - webnet
    volumes:
      - /bl_elg_gg_static/assets:/usr/src/bl_elg_gg/static/assets
      - /bl_elg_gg_static/posts:/usr/src/bl_elg_gg/static/posts

networks:
  webnet:
    external: true
