version: '3'
services:
  kava_redirect_nginx:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kava_redirect_nginx.rule=Host(`kava.elg.gg`)"
      - "traefik.http.routers.kava_redirect_nginx.entrypoints=web"
      - "traefik.http.routers.kava_redirect_nginx-secure.rule=Host(`kava.elg.gg`)"
      - "traefik.http.routers.kava_redirect_nginx-secure.entrypoints=websecure"
      - "traefik.http.routers.kava_redirect_nginx-secure.tls.certresolver=myresolver"
    networks:
      - webnet

networks:
  webnet:
    external: true
